# GitLeaks configuration to ignore false positives in generated code and documentation
title = "cryptoutil"

[allowlist]
	paths = [
		"api/client/",
		"api/model/",
		"api/server/",
		".github/workflows/"
	]
	regexes = [
		"A(256|192|128)GCM/A(256|192|128)(GCM)?KW",
		"A(256|192|128)GCM/dir",
		"A(256|192|128)GCM/RSA(-OAEP(-512|-384|-256)?|1_5)",
		"A(256|192|128)GCM/ECDH-ES(\\+A(256|192|128)KW)?",
		"A(256|192|128)CBC-HS(512|384|256)/A(256|192|128)(GCM)?KW",
		"A(256|192|128)CBC-HS(512|384|256)/dir",
		"A(256|192|128)CBC-HS(512|384|256)/RSA(-OAEP(-512|-384|-256)?|1_5)",
		"A(256|192|128)CBC-HS(512|384|256)/ECDH-ES(\\+A(256|192|128)KW)?",
		"(RS|PS|ES|HS)(256|384|512)|EdDSA"
	]

[[rules]]
	id = "ignore-documentation-examples"
	description = "Ignore documentation examples"
	filepath = "README\\.md"
	regex = "DB_PASSWORD|export BUNDLE_ENTERPRISE"
	tags = ["key", "Secret"]
